[site.info]
title = "Soliprem"
url = "https://soliprem.eu"
author = "Francesco Prem Solidoro"
email = "me@soliprem.eu"
description = ""
language = "en"
copyright = ""

[build]
content = "content"
output = "public"
deps = [
    "templates",
]
data = "_data"
minify = true

[build.assets]
nested = ["assets"]

[site.seo.feed]
enable = true
path = "feed.xml"

[site.seo.sitemap]
enable = false
path = "sitemap.xml"

[build.slug]
path = "safe"
fragment = "safe"

[build.hooks.css]
enable = true
command = ["tailwindcss"]
path = "assets/styles/style.css"

[site.header]
styles = []
scripts = []
elements = ['<link rel="alternate" type="application/rss+xml" href="/feed.xml">']

[serve]
interface = "127.0.0.1"
port = 5277
watch = true
